clc;clear all;
a=0.96;
b=0.77;
theta1deg=25;
theta2deg=45;
theta1=theta1deg*pi/180;
theta2=theta2deg*pi/180;
ax=a*cos(theta1);
ay=a*sin(theta1);
bx= ax + b*cos( theta2 + theta1 );
by= ay + b*sin( theta2 + theta1 );
x_axis_x_coord= [-2 2];
x_axis_y_coord= [0 0];
y_axis_x_coord= [0 0];
y_axis_y_coord= [-2 2];
a_x_coord=[0 ax];
a_y_coord=[0 ay];
b_x_coord=[ax bx];
b_y_coord=[ay by];
plot(x_axis_x_coord,x_axis_y_coord,'r',y_axis_x_coord,y_axis_y_coord,'r',a_x_coord,a_y_coord,'g',b_x_coord,b_y_coord,'b');
title("Forward Kinematics of 2R Robot");
